SET LINESIZE 200
SET PAGESIZE 50

SELECT 'EMPLOYEES' as table_name, COUNT(*) as row_count FROM employees
UNION ALL
SELECT 'WATER_UTILITY_ASSETS', COUNT(*) FROM water_utility_assets
UNION ALL
SELECT 'WATER_UTILITIES_WORK_ORDERS', COUNT(*) FROM water_utilities_work_orders
UNION ALL
SELECT 'WORKFORCE_ATTENDANCE', COUNT(*) FROM workforce_attendance
UNION ALL
SELECT 'WORKFORCE_PERFORMANCE', COUNT(*) FROM workforce_performance
UNION ALL
SELECT 'WORKFORCE_SCHEDULING', COUNT(*) FROM workforce_scheduling
UNION ALL
SELECT 'WORKFORCE_SKILLS', COUNT(*) FROM workforce_skills
UNION ALL
SELECT 'WORKFORCE_TRAINING', COUNT(*) FROM workforce_training
ORDER BY 1;

EXIT; 